# Generated by Django 3.1.12 on 2021-06-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='название на русском')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='название на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='название на японском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pokemons', verbose_name='изображение')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='появится')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='исчезнет')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='сила')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entities', to='pokemon_entities.pokemon', verbose_name='покемон')),
            ],
        ),
    ]
