# Generated by Django 3.1.12 on 2021-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(default='', max_length=200, verbose_name='название на русском'),
            preserve_default=False,
        ),
    ]
