# Generated by Django 3.1.12 on 2021-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonelementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='elements', to='pokemon_entities.PokemonElementType', verbose_name='типы стихий'),
        ),
    ]
