# Generated by Django 3.1.12 on 2021-06-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_pokemonelementtype_pokemons_by_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='pokemons_by_elements',
            field=models.ManyToManyField(blank=True, related_name='pokemons_by_type', to='pokemon_entities.Pokemon', verbose_name='покемоны'),
        ),
    ]
