# Generated by Django 3.1.12 on 2021-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20210616_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='pokemons_by_elements',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(blank=True, related_name='elements', to='pokemon_entities.PokemonElementType', verbose_name='типы стихий'),
        ),
    ]
